name: llvm toolchain
defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Run custom command before building'
        required: false
        type: string

jobs:
  build_llvm:
    name: Building LLVM and Clang
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    container:
        image: docker://ghcr.io/shinchiro/archlinux:latest
    steps:
      - name: Setup git config
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global pull.rebase true
          git config --global rebase.autoStash true
          git config --global fetch.prune true
          git config --global --add safe.directory $PWD

      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}

      - name: Loading clang root
        id: clang_root_cache
        uses: actions/cache/restore@v3
        with:
          path: clang_root
          key: ${{ secrets.CACHE_VERSION }}-clang_root
          restore-keys: ${{ secrets.CACHE_VERSION }}-clang_root

      - name: Loading x86_64 toolchain
        id: x86_64_cache
        uses: actions/cache/restore@main
        with:
          path: build_x86_64
          key: ${{ secrets.CACHE_VERSION }}-clang-x86_64_toolchain
          restore-keys: ${{ secrets.CACHE_VERSION }}-clang-x86_64_toolchain

      - name: Loading x86_64_v3 toolchain
        id: x86_64_v3_cache
        uses: actions/cache/restore@main
        with:
          path: build_x86_64_v3
          key: ${{ secrets.CACHE_VERSION }}-clang-x86_64_v3_toolchain
          restore-keys: ${{ secrets.CACHE_VERSION }}-clang-x86_64_v3_toolchain

      - name: Loading repository cache
        id: repository_cache
        if: false
        uses: actions/cache/restore@main
        with:
          path: src_packages
          key: ${{ secrets.CACHE_VERSION }}-repository
          restore-keys: ${{ secrets.CACHE_VERSION }}-repository

      - name: Running custom command
        if: ${{ github.event.inputs.command != '' }}
        continue-on-error: true
        run: ${{ github.event.inputs.command }}

      - name: Building LLVM with IR Profile Instrumentation
        if: ${{ steps.clang_root_cache.outputs.cache-matched-key == '' }}
        run: |
          cmake -DTARGET_ARCH=x86_64-w64-mingw32 -DLLVM_ENABLE_PGO=GEN -DCOMPILER_TOOLCHAIN=clang -DCMAKE_INSTALL_PREFIX=$PWD/clang_root -DMINGW_INSTALL_PREFIX=$PWD/build_x86_64/x86_64-w64-mingw32 -DSINGLE_SOURCE_LOCATION=$PWD/src_packages -DRUSTUP_LOCATION=$PWD/clang_root/install_rustup -G Ninja -B build_x86_64 -S $PWD
          ninja -C build_x86_64 llvm
          ninja -C build_x86_64 rustup
          ninja -C build_x86_64 cargo-clean

      - name: Building x86_64 toolchain
        if: ${{ steps.x86_64_cache.outputs.cache-matched-key == '' }}
        run: |
          cmake -DTARGET_ARCH=x86_64-w64-mingw32 -DLLVM_ENABLE_PGO=GEN -DCOMPILER_TOOLCHAIN=clang -DCMAKE_INSTALL_PREFIX=$PWD/clang_root -DMINGW_INSTALL_PREFIX=$PWD/build_x86_64/x86_64-w64-mingw32 -DSINGLE_SOURCE_LOCATION=$PWD/src_packages -DRUSTUP_LOCATION=$PWD/clang_root/install_rustup -G Ninja -B build_x86_64 -S $PWD
          ninja -C build_x86_64 llvm-clang

      - name: Building x86_64-v3 toolchain
        if: ${{ steps.x86_64_v3_cache.outputs.cache-matched-key == '' }}
        run: |
          cmake -DTARGET_ARCH=x86_64-w64-mingw32 -DLLVM_ENABLE_PGO=GEN -DCOMPILER_TOOLCHAIN=clang -DGCC_ARCH=x86-64-v3 -DCMAKE_INSTALL_PREFIX=$PWD/clang_root -DMINGW_INSTALL_PREFIX=$PWD/build_x86_64_v3/x86_64_v3-w64-mingw32 -DSINGLE_SOURCE_LOCATION=$PWD/src_packages -DRUSTUP_LOCATION=$PWD/clang_root/install_rustup -G Ninja -B build_x86_64_v3 -S $PWD
          ninja -C build_x86_64_v3 llvm-clang

      - name: PGO training with shaderc
        if: ${{ steps.clang_root_cache.outputs.cache-matched-key == '' }}
        run: |
          cmake -DTARGET_ARCH=x86_64-w64-mingw32 -DLLVM_ENABLE_PGO=GEN -DCLANG_PACKAGES_LTO=ON -DCOMPILER_TOOLCHAIN=clang -DCMAKE_INSTALL_PREFIX=$PWD/clang_root -DMINGW_INSTALL_PREFIX=$PWD/build_x86_64/x86_64-w64-mingw32 -DSINGLE_SOURCE_LOCATION=$PWD/src_packages -DRUSTUP_LOCATION=$PWD/clang_root/install_rustup -G Ninja -B build_x86_64 -S $PWD
          ninja -C build_x86_64 shaderc

      - name: Merging profraw to profdata
        if: ${{ steps.clang_root_cache.outputs.cache-matched-key == '' }}
        run: |
          llvm-profdata merge $PWD/clang_root/profiles/*.profraw -o llvm.profdata
          rm -rf $PWD/clang_root/profiles/* || true

      - name: Building LLVM with PGO
        if: ${{ steps.clang_root_cache.outputs.cache-matched-key == '' }}
        run: |
          cmake -DTARGET_ARCH=x86_64-w64-mingw32 -DLLVM_ENABLE_PGO=USE -DLLVM_PROFDATA_FILE="llvm.profdata" -DCOMPILER_TOOLCHAIN=clang -DCMAKE_INSTALL_PREFIX=$PWD/clang_root -DMINGW_INSTALL_PREFIX=$PWD/build_x86_64/x86_64-w64-mingw32 -DSINGLE_SOURCE_LOCATION=$PWD/src_packages -DRUSTUP_LOCATION=$PWD/clang_root/install_rustup -G Ninja -B build_x86_64 -S $PWD
          ninja -C build_x86_64 llvm

      - name: Cleanup
        run: |
          rm -rf {build_x86_64,build_x86_64_v3}/{toolchain,packages} || true

      - name: Collecting logs
        if: always()
        run: |
          mkdir -p build_x86_64_logs
          cp -fr $(find build_x86_64 -type f -iname "*-*.log") build_x86_64_logs || true
          7z a -m0=lzma2 -mx=9 -ms=on logs.7z build*logs

      - name: Uploading logs
        uses: actions/upload-artifact@v4  # Changed to stable version
        if: always()
        with:
          name: logs
          path: logs.7z
          retention-days: 1

      - name: Uploading toolchain
        uses: actions/upload-artifact@v4  # Changed to stable version
        if: always()
        with:
          name: toolchain
          path: clang_root

      - name: Saving clang root
        uses: actions/cache/save@v3  # Changed to stable version
        with:
          path: clang_root
          key: ${{ secrets.CACHE_VERSION }}-clang_root

      - name: Saving x86_64 toolchain
        uses: actions/cache/save@main
        with:
          path: build_x86_64
          key: ${{ secrets.CACHE_VERSION }}-clang-x86_64_toolchain

      - name: Saving x86_64_v3 toolchain
        uses: actions/cache/save@main
        with:
          path: build_x86_64_v3
          key: ${{ secrets.CACHE_VERSION }}-clang-x86_64_v3_toolchain

      - name: Saving repository cache
        if: false
        uses: actions/cache/save@main
        with:
          path: src_packages
          key: ${{ secrets.CACHE_VERSION }}-repository

  call_workflow:
    name: Run mpv_clang
    runs-on: ubuntu-latest
    needs: build_llvm
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use built-in token
    steps:
      - name: Trigger mpv_clang workflow
        run: |
          curl -s -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/mpv_clang.yml/dispatches" \
            -d '{
              "ref": "${{ github.ref }}",
              "inputs": {
                "sourceforge": "false",
                "github_release": "false",
                "mpv_tarball": "false"
              }
            }'
          EOF